# Generated by Django 6.0.2 on 2026-02-04 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employee_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Employee",
            new_name="Employees",
        ),
    ]
